const BASE_URL_PRODUCT = "http://localhost:8000/products/";
const BASE_URL_PRODUCT_TYPES = "http://localhost:8000/product-types/";

//call API fetch products
const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";


//call API, get product Id
const FETCH_PRODUCT_BY_ID_PENDING = "FETCH_PRODUCT_BY_ID_PENDING";
const FETCH_PRODUCT_BY_ID_SUCCESS = "FETCH_PRODUCT_BY_ID_SUCCESS";
const FETCH_PRODUCT_BY_ID_ERROR = "FETCH_PRODUCT_BY_ID_ERROR";


//call API, get product types
const FETCH_PRODUCT_TYPES_PENDING = "FETCH_PRODUCT_TYPES_PENDING";
const FETCH_PRODUCT_TYPES_SUCCESS = "FETCH_PRODUCT_TYPES_SUCCESS";
const FETCH_PRODUCT_TYPES_ERROR = "FETCH_PRODUCT_TYPES_ERROR";


export {
    BASE_URL_PRODUCT,
    BASE_URL_PRODUCT_TYPES,
    FETCH_PRODUCTS_PENDING, 
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_ERROR,
    FETCH_PRODUCT_BY_ID_PENDING,
    FETCH_PRODUCT_BY_ID_SUCCESS,
    FETCH_PRODUCT_BY_ID_ERROR,
    FETCH_PRODUCT_TYPES_PENDING,
    FETCH_PRODUCT_TYPES_SUCCESS,
    FETCH_PRODUCT_TYPES_ERROR,
};