const VALUE_PRODUCT_NAME_INPUT = "VALUE_PRODUCT_NAME_INPUT";
const VALUE_MIN_PRICE_INPUT = "VALUE_MIN_PRICE_INPUT";
const VALUE_MAX_PRICE_INPUT = "VALUE_MAX_PRICE_INPUT";
const VALUE_PRODUCT_TYPE_SELECT = "VALUE_PRODUCT_TYPE_SELECT"
const GET_ALL_PRODUCT_FILTER = "GET_ALL_PRODUCT_FILTER";

export {
    VALUE_PRODUCT_NAME_INPUT,
    VALUE_MIN_PRICE_INPUT,
    VALUE_MAX_PRICE_INPUT,
    VALUE_PRODUCT_TYPE_SELECT,
    GET_ALL_PRODUCT_FILTER
};